// Pre-trained Beacon Treasury Master Domain Knowledge & Real QA Test Cases from Maseera Sayyed

export interface BeaconTrainedTestCase {
  testCaseId: string;
  testModule: string;
  featureTab: string;
  testScenario: string;
  testCases: string;
  testInputs: string;
  expectedResult: string;
  actualResult: string;
  status: string;
}

export const BEACON_ARCHITECTURE_BLUEPRINT = `
BEACON TREASURY MASTER — CORE PRODUCT ARCHITECTURE & QA STANDARDS (Trained from Maseera Sayyed's QA Suites):
1. UI & Action Workflows ("Initiate Action"):
   - Deals support lifecycle actions under the "Initiate Action" menu:
     • Sanction / ECB: "Update Sanction", "Renew Sanction", "Add Deviation", "Change Disbursement Schedule".
     • Mutual Fund (MF): "Investment", "Redemption", "Switch", "Split Action" (Split Out / Split In), "MF Modification".
   - Authorization & Access Rights:
     • Role separation between "input access rights" (Maker) and "authorization rights" (Checker).
     • Users without input rights cannot edit deals or perform bulk import; users with input-only rights cannot authorize deals.
     • Transactions in "Pending Authorization" status enforce strict dependency checks (e.g., cannot perform Split Out if first investment transaction is Pending Authorization; if a Redemption is Pending Authorization, post-split authorization is blocked if it results in a negative unit balance).

2. Bulk Import / Bulk Upload Architecture:
   - Standard Bulk Import UI includes "Save Sample" (generates template with proper column headers and sample entries without client-specific names/data) and "Accept" button.
   - Excel File Format Rule: Column headers MUST start from the 5th row, and deal data MUST start from the 6th row. Header mapping is positional (based on defined column number and row position — row 5 headers, row 6 data) even if header text differs slightly.
   - Date & Duplicate Validations: Deals/files with dates beyond the Server Date / System Date are blocked; duplicate Trade No. or mismatched Sanction References across sheets (Basic Details, Main Break-up, Sub Break-up) are rejected with proper validation messages.

3. Module-Specific Business Rules:
   - Term Loan (Penalty, Cashflow, Overdue Report, Autopay Overdue Report):
     • Penalty entries (penalty interest %, penalty principal %) appear in Deal Cashflow and Overdue Report ONLY when overdue occurs AFTER loan disbursement AND default/penalty rate > 0.
     • Without loan disbursement (or if penalty rate is 0 / not entered), penalty entries are NOT generated in Cashflow or Overdue Report.
     • Autopay Overdue Report: Deals under Autopay do NOT appear in the Overdue Report during the active autopay period; once the autopay period ends, any subsequent overdue appears in the Overdue Report with penalty entries.
   - TREPS Investment (Bulk Import & Deal Entry):
     • Mandatory fields: Trade No., Maturity Date, Settlement Date, Trade Interest Rate (%), Trade Value (Rs.).
     • Field Mapping & Calculations: 1 Leg Consideration (Principal) = Trade Value in Excel; Trade Interest Rate (%) = Repo Rate in Excel; Reversal Date for Lend = Maturity Date in Excel; calculates Tenure, Settlement Type, Total Interest, and 2-Leg Consideration (Principal + Interest).
   - Daily Cash Flow MIS Report:
     • "Short Capitalized Interest Payment" flag and "Capitalized Interest Payment" flag control whether unprocessed interest is included in the summary and how the "Running Balance" is calculated.
   - Sanction Master, ECB Deal, Sanction Report & Sanction Bulk Upload:
     • "Currency" field is visible and editable ONLY for ECB instrument; non-editable for all other instruments and non-editable in fungible sanctions even for ECB.
     • "Has Sub Limit" checkbox is set to NO / non-editable in ECB main break-up; if "Has Sub Limit" is NO, adding sub break-up details is restricted.
     • Sanction Facility ID visibility: If sanction is in FCY, Facility ID is visible only when deal currency matches sanction FCY; if sanction is in INR, Facility ID is visible for all deals irrespective of deal currency.
     • Sanction Utilization: FCY sanction + FCY deal = validated directly on FCY drawdown without INR conversion; INR sanction + FCY deal = validated as (FCY drawdown * conversion rate) = INR amount. Cumulative utilization is tracked across multiple deals; drawdown/deviation cannot exceed available sanction or reduce sanction below utilized amount during Update/Renewal/Add Deviation/Change Disbursement Schedule.
     • Repayment amount in Change Disbursement Schedule must match disbursement amount (cannot be greater or less).
     • Sanction Report displays Currency column and calculates Principal O/S in INR using conversion rate.
   - CC/OD and Bank Balance Master:
     • Header displayed as "Actual Closing Balance".
     • Updated closing balance reflects in Cashflow, ALM Treasury Report, and Borrowing Register Report from the same effective date, and interest calculation starts from that date.
     • Negative bank balance rules: Restricted after sanction validity period expires, restricted if no CC/OD deal is linked, restricted beyond sanctioned limit, and restricted for "tracking-purpose" bank accounts.
     • Positive bank balance rules: Allowed even when no CC/OD deal is linked and allowed for tracking-purpose bank accounts.
     • On sanction validity date, closing balance for a linked CC/OD deal must be 0 or positive.
     • CC Bank Account dropdown on Deal UI displays only Home Entity bank accounts linked to the selected lender bank.
   - Mutual Fund (MF Split Action):
     • Under Initiate Action -> Split Action: user enters Ratio (New:Old) for ISIN split.
     • "Split Out From" dropdown filters schemes belonging ONLY to the same AMC and matching Plan, Option, and Fund Name as the selected Split In deal.
     • Split In deal must have no previous transactions prior to Split Action; Value Date in Split In is auto-fetched from Split Out transaction; calculates Split In Units and new ISIN NAV from split ratio.
     • Updates Investment Holding Details, Transaction History, and Holding Summary (Total Units, Average Purchase NAV, Total Investment Amount, Current Market Value, Unrealised/Realised Profit/Loss, Historical XIRR & Current XIRR).
     • Post-Split Restrictions: Once all units are Split Out, only "MF Modification" is available under Initiate Action (Investment, Redemption, Switch hidden); Split Action option is removed from a deal where Split In is already completed.

4. Maseera Sayyed's Exact QA Writing Style:
   - Test Scenario: Starts with "Validate ..." or "Verify ..." — clear, specific functional condition.
   - Test Cases: Starts with "Verify that ..." (or "Ensure that ...") naming the exact Beacon screen, tab, field, flag, or report.
   - Expected Result: Direct specification statements ("The system should ...", "System should restrict / allow ... and display an appropriate validation message.").
   - Actual Result: Clear confirmation matching Expected Result ("The system prevents ... and displays the appropriate validation message.").
`;

export const BEACON_TRAINED_TEST_CASES: BeaconTrainedTestCase[] = [
  // 1. Term Loan — Penalty, Cashflow, Overdue Report & Autopay Overdue Report
  {
    testCaseId: 'TC01',
    testModule: 'Term Loan',
    featureTab: 'penalty',
    testScenario: 'Penalty entries appear in the cashflow when overdue occurs after loan disbursement.',
    testCases: 'Verify that penalty is applied and displayed in cashflow when interest or principal becomes overdue after disbursement.',
    testInputs: 'TL-23-24-00001, penalty interest - 10%, penalty principal - 10%',
    expectedResult: 'The cashflow should display the deal with penalty entries whenever overdue occurs on interest or principal after loan disbursement.',
    actualResult: 'The cashflow is displaying the deal with penalty entries.',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'Term Loan',
    featureTab: 'penalty',
    testScenario: 'Penalty entries are not displayed in the cashflow without loan disbursement.',
    testCases: 'Verify that penalty is not applied and displayed in cashflow when interest or principal becomes overdue without disbursement.',
    testInputs: 'TL-24-25-00002, penalty interest - 10%, penalty principal - 10%',
    expectedResult: 'If no disbursement has occurred, penalty entries should not be displayed in Cashflow.',
    actualResult: 'Penalty entries are not being displayed in cashflow.',
    status: 'pass',
  },
  {
    testCaseId: 'TC03',
    testModule: 'Term Loan',
    featureTab: 'overdue report',
    testScenario: 'After disbursement, overdue deals appear in the overdue report with penalty entries.',
    testCases: 'Verify that penalty is applied and reflected in the overdue report when interest or principal becomes overdue after disbursement.',
    testInputs: 'TL-24-25-00002, penalty interest - 10%, penalty principal - 10%',
    expectedResult: 'The overdue report should display the deal with penalty entries, whenever there is an overdue on interest or principal after loan disbursement.',
    actualResult: 'The overdue report correctly displays the deal with penalty entries.',
    status: 'pass',
  },
  {
    testCaseId: 'TC04',
    testModule: 'Term Loan',
    featureTab: 'overdue report',
    testScenario: 'No disbursement, deal appears in the overdue report without penalty entries.',
    testCases: 'Verify that if no disbursement has been made, then the deal should not appear in the overdue report.',
    testInputs: 'TL-24-25-00002, penalty interest - 10%, penalty principal - 10%',
    expectedResult: 'When no disbursement is done, the deal should not be displayed in the overdue report, and no penalty entries should be shown.',
    actualResult: 'The deal is not displayed in the overdue report, and no penalty entries are shown.',
    status: 'pass',
  },
  {
    testCaseId: 'TC05',
    testModule: 'Term Loan',
    featureTab: 'Autopay overdue report',
    testScenario: 'Deal under autopay until 31st March 2024, not visible in overdue report; after autopay ends, if overdue occurs, deal appears in overdue report with penalty entries.',
    testCases: 'Verify that the deal does not appear in the overdue report during the autopay period, and after the autopay ends, if overdue occurs, the deal appears in the overdue report with penalty entries.',
    testInputs: 'TL-23-24-00004, penalty interest - 10%, penalty principal - 10%',
    expectedResult: 'For a deal under autopay until 31st March 2024, Deal does not appear in the overdue report till the autopay period ends. Once the autopay period ends, the deal should appear in the overdue report, and Penalty entries are displayed only for overdues occurring after the autopay period.',
    actualResult: 'The deal appears in the overdue report after 31st March 2024, and penalty entries are shown only for overdues occurring after the autopay period.',
    status: 'pass',
  },
  {
    testCaseId: 'TC06',
    testModule: 'Term Loan',
    featureTab: 'penalty',
    testScenario: 'Default interest/principal rate is not entered, penalty not displayed in cashflow/overdue report when overdue occurs.',
    testCases: 'Verify that when default interest/principal rate is not entered, penalty is not displayed in the cashflow/overdue report when overdue occurs, irrespective of whether disbursement has been made or not.',
    testInputs: 'TL-23-24-00008, penalty interest - 0, penalty principal - 0',
    expectedResult: 'Penalty entries should not be generated when an overdue occurs and no default/penalty rate is defined.',
    actualResult: 'No penalty entries were generated when the overdue occurred, as no default/penalty rate was defined.',
    status: 'pass',
  },

  // 2. TREPS Investment — Bulk Import
  {
    testCaseId: 'TC01',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Attempt to import a .csv/.xlsx file in the prescribed format.',
    testCases: 'Verify that a user with investment input access rights is able to successfully import the file.',
    testInputs: 'data given by client',
    expectedResult: 'Imported deals should be displayed on the Bulk Import UI with all mandatory columns and entries populated correctly.',
    actualResult: 'Deals are displayed properly on the Bulk Import UI with correct columns and entries.',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Accept the imported sheet/datafile using the Accept button on the Bulk Import UI.',
    testCases: 'Verify that deals displayed on the Bulk Import UI are accepted without errors, and invalid deals are handled appropriately.',
    testInputs: 'data given by client',
    expectedResult: 'Deals with correct entries should be accepted successfully. If any deal has incorrect data, the system should not accept it and should display the proper error message.',
    actualResult: 'Deals with correct entries are accepted, while invalid deals are not accepted and appropriate error messages are shown.',
    status: 'pass',
  },
  {
    testCaseId: 'TC03',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate Excel file format for bulk import.',
    testCases: 'Verify that in the Excel/bulk import file: Column headers should start from the 5th row. Deal data should start from the 6th row. If this format is not followed, the deal should not be accepted in the bulk import UI.',
    testInputs: 'data given by client',
    expectedResult: 'Deals should only be accepted if the column headers begin from row 5 and the data begins from row 6. Any deviation from this format should result in rejection with an appropriate error message.',
    actualResult: 'Column headers and deal data were in the correct rows (5th and 6th respectively). Deals were accepted successfully as per the required format.',
    status: 'pass',
  },
  {
    testCaseId: 'TC04',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate header mapping based on column/row position during bulk import.',
    testCases: 'Verify that even if the header text in the Excel/bulk import file does not exactly match the UI field names, the system should correctly identify and fetch the data based on the defined column number and row position (headers at row 5, data starting from row 6).',
    testInputs: 'data given by client',
    expectedResult: 'The system should fetch and map data correctly from the Excel file to the UI fields using the column/row positions, even if header text differs.',
    actualResult: 'Data was fetched and mapped correctly from the Excel file to the UI fields based on column/row positions, even though header text did not exactly match.',
    status: 'pass',
  },
  {
    testCaseId: 'TC05',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Use the Save Sample option to generate a sample import file.',
    testCases: 'Verify that using Save Sample generates a file in the correct format without specific client names or client data.',
    testInputs: 'data given by client',
    expectedResult: 'The file should be saved with proper column headers, no client-specific names/data, and only a few sample entries for reference.',
    actualResult: 'The file should be saved with proper column headers, no client-specific names/data, and only a few sample entries.',
    status: 'pass',
  },
  {
    testCaseId: 'TC06',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate deal acceptance based on settlement date.',
    testCases: 'Verify that a deal with a settlement date in the future is not accepted when the system date is 01-Jan-2025.',
    testInputs: 'data given by client',
    expectedResult: 'Deals with a future settlement date should be rejected, and an appropriate error message should be displayed.',
    actualResult: 'Deals with a future settlement date were correctly rejected, and the system displayed the appropriate error message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC07',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Prevent importing deals/files beyond the server date and display proper error message.',
    testCases: 'Verify that deals or files with a date later than the server date are not imported.',
    testInputs: 'data given by client',
    expectedResult: 'The system should block the import and display a clear, proper error message indicating that the deal/file date cannot be beyond the server date.',
    actualResult: 'The system blocked the import and displayed the proper error message successfully.',
    status: 'pass',
  },
  {
    testCaseId: 'TC08',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate mandatory field "Trade No" during bulk import.',
    testCases: 'Verify that any row in the Excel file with a blank Trade No. is not displayed on the Bulk Import UI.',
    testInputs: 'data given by client',
    expectedResult: 'Rows with blank Trade No should be rejected, and an appropriate error message should be shown.',
    actualResult: 'Rows with blank Trade No were rejected, and the error message was displayed correctly.',
    status: 'pass',
  },
  {
    testCaseId: 'TC09',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate mandatory field "Maturity Date" during bulk import.',
    testCases: 'Verify that any row in the Excel file missing the Maturity Date is not displayed on the Bulk Import UI.',
    testInputs: 'data given by client',
    expectedResult: 'Rows without a Maturity Date should be rejected, and an appropriate error message should be displayed.',
    actualResult: 'Rows missing the Maturity Date were correctly rejected, and the proper error message was shown.',
    status: 'pass',
  },
  {
    testCaseId: 'TC10',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate mandatory field "Settlement Date" during bulk import.',
    testCases: 'Verify that any row in the Excel file missing the Settlement Date is not displayed on the Bulk Import UI.',
    testInputs: 'data given by client',
    expectedResult: 'Rows without a Settlement Date should be rejected, and an appropriate error message should be displayed.',
    actualResult: 'Rows missing the Settlement Date were correctly rejected, and the proper error message was shown.',
    status: 'pass',
  },
  {
    testCaseId: 'TC11',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate mandatory and valid fields "Trade Interest Rate(%)" and "Trade Value (Rs.)" during bulk import.',
    testCases: 'Verify that if "Trade Interest Rate(%)" or "Trade Value (Rs.)" is invalid or left blank in the Excel file, an appropriate error message is displayed.',
    testInputs: 'data given by client',
    expectedResult: 'Rows with invalid or blank values in these fields should be rejected, and a proper error message should be shown.',
    actualResult: 'The system correctly rejected invalid or blank values and displayed the appropriate error message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC12',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate edit and bulk import restrictions for users without input rights.',
    testCases: 'Verify that a user without investment input access rights is unable to edit deals or perform bulk import.',
    testInputs: 'data given by client',
    expectedResult: 'Users without input rights should be restricted from editing deals or performing bulk import, and an appropriate error message should be displayed.',
    actualResult: 'Test executed successfully - users without input rights were restricted as expected.',
    status: 'pass',
  },
  {
    testCaseId: 'TC13',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Verify authorization restrictions for users with input-only access.',
    testCases: 'Ensure that a user with only input access rights is unable to authorize deals.',
    testInputs: 'data given by client',
    expectedResult: 'Users without authorization rights should be restricted from authorizing deals, and an appropriate error message should be displayed.',
    actualResult: 'User was unable to authorize deals, and the proper error message was displayed.',
    status: 'pass',
  },
  {
    testCaseId: 'TC14',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate duplicate Trade No. restriction during deal entry.',
    testCases: 'Verify that a deal with a Trade No. already existing in the system is not accepted.',
    testInputs: 'data given by client',
    expectedResult: 'Deals with duplicate Trade No. should be rejected, and an appropriate duplicate error message should be displayed.',
    actualResult: 'Deals with duplicate Trade No. were rejected, and the correct error message was displayed.',
    status: 'pass',
  },
  {
    testCaseId: 'TC15',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate field mapping and data accuracy during bulk import.',
    testCases: 'Verify that the following fields from the Excel/bulk import file are correctly reflected in the UI: 1 Leg Consideration (Principal) matches Trade Value in Excel; Trade Interest Rate (%) matches Repo Rate in Excel; Reversal Date for Lend matches Maturity Date in Excel; Settlement Date matches in both Excel and UI; Tenure and Settlement Type are calculated and displayed correctly.',
    testInputs: 'data given by client',
    expectedResult: 'All fields from the Excel/bulk import file should be accurately displayed in the UI, with tenure and settlement type correctly derived.',
    actualResult: 'All fields from the Excel/bulk import file were accurately displayed in the UI.',
    status: 'pass',
  },
  {
    testCaseId: 'TC16',
    testModule: 'Treps Investment',
    featureTab: 'bulk import',
    testScenario: 'Validate calculation of total interest and 2-leg consideration during deal import.',
    testCases: 'Verify that the system correctly calculates: Total Interest based on Trade Value, Trade Interest Rate (%), Tenure, and relevant dates, and 2-Leg Consideration (Amount) including principal and interest components.',
    testInputs: 'data given by client',
    expectedResult: 'Total interest and 2-leg consideration amounts should be calculated accurately and displayed correctly in the UI.',
    actualResult: 'Total interest and 2-leg consideration amounts were calculated correctly and displayed as expected.',
    status: 'pass',
  },

  // 3. Daily Cash Flow MIS Report — Capitalized Interest Flag & Running Balance
  {
    testCaseId: 'TC01',
    testModule: 'Cashflow Report',
    featureTab: 'Daily Cash Flow MIS Report',
    testScenario: 'Validate the resolution of the running balance issue when the Short Capitalized Interest Payment flag is enabled.',
    testCases: 'Verify that the Running Balance in the Daily Cash Flow MIS Report is correctly calculated and updated when the Short Capitalized Interest Payment flag is checked.',
    testInputs: 'Short Capitalized Interest Payment flag = Checked',
    expectedResult: 'The Running Balance should be calculated correctly by considering the applicable short capitalized interest payment amount when the flag is enabled.',
    actualResult: 'The Running Balance was correctly calculated and updated when the Short Capitalized Interest Payment flag was enabled.',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'Cashflow Report',
    featureTab: 'Daily Cash Flow MIS Report',
    testScenario: 'Validate the running balance and summary display when the Capitalized Interest Payment flag is not enabled.',
    testCases: 'Verify that when the Capitalized Interest Payment flag is unchecked and the interest payment has not yet been processed, the interest amount is not included in the summary and the Running Balance is calculated correctly based only on the applicable transactions.',
    testInputs: 'Capitalized Interest Payment flag = Unchecked',
    expectedResult: 'If the interest payment has not been processed and the Capitalized Interest Payment flag is unchecked, the interest amount should not be reflected in the summary. The Running Balance should be calculated correctly based on the actual processed transactions.',
    actualResult: 'When the Capitalized Interest Payment flag was unchecked and the interest payment had not been processed, the interest amount was not reflected in the summary and the Running Balance was calculated correctly.',
    status: 'pass',
  },

  // 4. Sanction Master / ECB Deal / Sanction Report / Sanction Bulk Upload
  {
    testCaseId: 'TC01',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate "Currency" field behavior in Sanction Master',
    testCases: 'Verify that "Currency" field is visible, editable, and dropdown is available in Sanction Master.',
    testInputs: 'Sanction Master UI',
    expectedResult: '"Currency" field should be visible and editable in Sanction Master, and dropdown should be available with currency options.',
    actualResult: '"Currency" field is visible and editable in Sanction Master, and dropdown is available with options.',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate visibility of Sanction Facility ID based on currency',
    testCases: 'Verify that Sanction Facility ID is visible only when deal currency matches sanction FCY, and for INR sanction it is visible irrespective of deal currency.',
    testInputs: 'FCY Sanction & INR Sanction',
    expectedResult: 'If sanction is created in FCY, then Facility ID should be visible only when deal is created in the same FCY. If sanction is created in INR, then Facility ID should be visible for all deals irrespective of deal currency.',
    actualResult: 'System shows Facility ID only when FCY matches, and for INR sanction it is visible for all deal currencies.',
    status: 'pass',
  },
  {
    testCaseId: 'TC03',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate currency field editability based on instrument type',
    testCases: 'Verify that "Currency" field is not editable for all instruments except ECB.',
    testInputs: 'Instrument Type = ECB vs Non-ECB',
    expectedResult: '"Currency" field should be editable only for ECB instrument. For all other instruments, "Currency" field should be non-editable.',
    actualResult: 'System allows currency edit only for ECB and restricts editing for other instruments.',
    status: 'pass',
  },
  {
    testCaseId: 'TC04',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate currency field editability in fungible sanction for ECB',
    testCases: 'Verify that "Currency" column is not editable in fungible sanction for ECB.',
    testInputs: 'Fungible Sanction for ECB',
    expectedResult: '"Currency" column should be non-editable in fungible sanction even for ECB.',
    actualResult: 'System does not allow editing of "Currency" column in fungible sanction for ECB.',
    status: 'pass',
  },
  {
    testCaseId: 'TC05',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate editability of "Has Sub Limit" checkbox in ECB main break-up',
    testCases: 'Verify that "Has Sub Limit" checkbox is not editable in ECB main break-up.',
    testInputs: 'ECB Main Break-up',
    expectedResult: '"Has Sub Limit" checkbox should be non-editable in ECB main break-up.',
    actualResult: 'System does not allow editing of "Has Sub Limit" checkbox in ECB main break-up.',
    status: 'pass',
  },
  {
    testCaseId: 'TC06',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate multiple break-ups with different currencies under same sanction reference',
    testCases: 'Verify that user is not allowed to add multiple break-ups with different currencies under the same sanction reference.',
    testInputs: 'Multiple break-ups with different currencies',
    expectedResult: 'System should not allow adding multiple break-ups with different currencies under the same sanction reference.',
    actualResult: 'System does not allow adding multiple break-ups with different currencies under the same sanction reference.',
    status: 'pass',
  },
  {
    testCaseId: 'TC07',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction utilization in FCY without INR conversion',
    testCases: 'Verify that when sanction and deal are created in FCY, the sanction utilization validation is applied on FCY drawdown amount and not converted to INR.',
    testInputs: 'FCY Sanction + FCY Deal',
    expectedResult: 'Sanction utilization should be validated based on FCY drawdown amount only, without converting it to INR.',
    actualResult: 'Sanction utilization is validated based on FCY drawdown amount and no INR conversion is applied.',
    status: 'pass',
  },
  {
    testCaseId: 'TC08',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction utilization when sanction is in INR and deal is in FCY',
    testCases: 'Verify that when sanction is in INR and deal is created in any FCY, sanction utilization validation is applied based on (FCY drawdown * conversion rate) = INR amount.',
    testInputs: 'INR Sanction + FCY Deal',
    expectedResult: 'Sanction utilized amount should be calculated as (FCY drawdown * conversion rate) = INR amount and validated accordingly against sanction limit.',
    actualResult: 'System calculates sanction utilized amount as (FCY drawdown * conversion rate) and applies validation correctly.',
    status: 'pass',
  },
  {
    testCaseId: 'TC09',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction limit restriction across multiple deals',
    testCases: 'Verify that system restricts drawdown when user tries to exceed sanction limit and also prevents usage of same sanction in another deal when available sanction is 0.',
    testInputs: 'Drawdown > Available Sanction',
    expectedResult: 'System should not allow drawdown amount exceeding the sanction limit. When available sanction becomes 0, the same sanction should not be allowed to be used in another deal.',
    actualResult: 'System restricts excess drawdown and does not allow usage of sanction in another deal when available limit is 0.',
    status: 'pass',
  },
  {
    testCaseId: 'TC10',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate cumulative sanction utilization across multiple deals',
    testCases: 'Verify that when same Sanction Facility ID is used in multiple deals (within limit), system calculates cumulative utilized amount correctly.',
    testInputs: 'Multiple Deals under same Sanction Facility ID',
    expectedResult: 'System should allow usage of same sanction in another deal if limit is not exhausted, and cumulative utilization across all deals should not exceed sanction limit.',
    actualResult: 'System allows usage of same sanction in multiple deals within limit and calculates cumulative utilization correctly.',
    status: 'pass',
  },
  {
    testCaseId: 'TC11',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate update restrictions on existing sanction',
    testCases: 'Verify that system does not allow changing currency and restricts sanction amount to be less than utilized amount during initiate action.',
    testInputs: 'Initiate Action -> Update Sanction',
    expectedResult: 'System should not allow changing currency of an existing sanction. System should not allow updating sanction amount less than the already utilized amount.',
    actualResult: 'System restricts currency change and does not allow sanction amount to be updated below utilized amount.',
    status: 'pass',
  },
  {
    testCaseId: 'TC12',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate restrictions during sanction renewal',
    testCases: 'Verify that during sanction renewal, system does not allow currency change and restricts sanction amount to be less than utilized amount.',
    testInputs: 'Initiate Action -> Renew Sanction',
    expectedResult: 'System should not allow changing the currency during sanction renewal. System should not allow updating sanction amount less than the already utilized amount.',
    actualResult: 'System restricts currency change and does not allow sanction amount to be updated below utilized amount during renewal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC13',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'Sanction Master',
    testScenario: 'Validate restriction on multiple break-ups with different currencies during update and renewal of sanction',
    testCases: 'Verify that system does not allow adding multiple break-ups with different currencies under the same sanction reference while using initiate action (Update Sanction / Renew Sanction).',
    testInputs: 'Update Sanction / Renew Sanction',
    expectedResult: 'System should restrict adding break-ups with different currencies under the same sanction reference during update and renewal of sanction.',
    actualResult: 'System restricts adding multiple break-ups with different currencies under the same sanction reference during update and renewal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC14',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction limit checks during Add Deviation via initiate action',
    testCases: 'Verify that system restricts deviation amount based on available sanction and applies correct validation logic for FCY and INR sanctions.',
    testInputs: 'Initiate Action -> Add Deviation',
    expectedResult: 'System should not allow deviation amount more than available sanction. System should not allow deviation when available balance is zero. If sanction is in FCY, validation should be applied on FCY drawdown amount. If sanction is in INR, validation should be applied on (FCY drawdown * conversion rate) = INR amount.',
    actualResult: 'System restricts deviation beyond available sanction, blocks action when balance is zero, and applies correct validation for both FCY and INR scenarios.',
    status: 'pass',
  },
  {
    testCaseId: 'TC15',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction limit checks during Change Disbursement Schedule via initiate action',
    testCases: 'Verify that system applies same validation rules during Change Disbursement Schedule as applied in Add Deviation.',
    testInputs: 'Initiate Action -> Change Disbursement Schedule',
    expectedResult: 'System should not allow disbursement amount more than available sanction and should block action when available balance is zero, applying FCY and INR conversion rules accurately.',
    actualResult: 'System applies all validation checks correctly during Change Disbursement Schedule as per defined rules.',
    status: 'pass',
  },
  {
    testCaseId: 'TC16',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate repayment amount against disbursement during Change Disbursement via initiate action',
    testCases: 'Verify that system restricts adding repayment amount more or less than disbursement amount during Change Disbursement.',
    testInputs: 'Change Disbursement Schedule',
    expectedResult: 'System should not allow repayment amount to be greater or less than the disbursement amount and should enforce matching values.',
    actualResult: 'System restricts adding repayment amount different from disbursement amount.',
    status: 'pass',
  },
  {
    testCaseId: 'TC17',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate disbursement and repayment schedule via Add Deviation and Change Disbursement Schedule',
    testCases: 'Verify that system allows adding disbursement schedule within available sanction limit through Add Deviation and Change Disbursement Schedule, with proper repayment schedule and history tracking.',
    testInputs: 'Add Deviation & Change Disbursement Schedule',
    expectedResult: 'System should allow adding disbursement schedule within available sanction limit. Proper repayment schedule should be maintained and all changes should be captured and visible in history.',
    actualResult: 'System allows adding disbursement schedule within limit, maintains proper repayment schedule, and updates are correctly reflected in history.',
    status: 'pass',
  },
  {
    testCaseId: 'TC18',
    testModule: 'Sanction Master ECB deal',
    featureTab: 'sanction report',
    testScenario: 'Validate currency column and amount calculation in Sanction Report',
    testCases: 'Verify that new currency column is added correctly, sanction currency is displayed properly, header naming is correct, and Principal O/S in INR is calculated and shown accurately.',
    testInputs: 'Sanction Report',
    expectedResult: 'Currency column should be added and visible in sanction report. Sanction currency should be displayed correctly. Header name should be proper and meaningful. Principal O/S in INR should be calculated using correct conversion rate and displayed accurately.',
    actualResult: 'Currency column is added correctly, sanction currency is visible, header naming is proper, and Principal O/S in INR is calculated and displayed correctly.',
    status: 'pass',
  },
  {
    testCaseId: 'TC19',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate currency column and dropdown in Sanction Bulk Upload',
    testCases: 'Verify that "Currency" column is present in Sanction Bulk Upload and dropdown is available with valid currency options.',
    testInputs: 'Sanction Bulk Upload template',
    expectedResult: '"Currency" column should be visible in bulk upload. Dropdown should be available with valid currency options.',
    actualResult: '"Currency" column is visible and dropdown is available with valid options in bulk upload.',
    status: 'pass',
  },
  {
    testCaseId: 'TC20',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sanction reference consistency between basic details and main break-up',
    testCases: 'Verify that system throws validation error when sanction reference in basic details and main break-up are different.',
    testInputs: 'Sanction Bulk Upload',
    expectedResult: 'System should not allow mismatch and should show proper error message if sanction reference differs between basic details and main break-up.',
    actualResult: 'System throws proper validation error when sanction reference is different in basic details and main break-up.',
    status: 'pass',
  },
  {
    testCaseId: 'TC21',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate availability date in sub break-up against main break-up',
    testCases: 'Verify that system throws validation error when sub break-up availability date is greater than main break-up availability date.',
    testInputs: 'Sanction Bulk Upload',
    expectedResult: 'System should restrict and show proper error message if sub break-up availability date exceeds main break-up availability date.',
    actualResult: 'System throws proper validation error message when sub break-up availability date is greater.',
    status: 'pass',
  },
  {
    testCaseId: 'TC22',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sub break-up sheet behavior when "Has Sub Limit" is set to NO',
    testCases: 'Verify that system throws validation error when user selects "Has Sub Limit" as NO and still adds details in sub break-up sheet.',
    testInputs: 'Has Sub Limit = NO',
    expectedResult: 'System should throw validation error and not allow submission when "Has Sub Limit" is NO but sub break-up details are provided.',
    actualResult: 'System throws validation error when sub break-up details are added despite "Has Sub Limit" being NO.',
    status: 'pass',
  },
  {
    testCaseId: 'TC23',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate usage of existing sanction reference',
    testCases: 'Verify that system allows using the same sanction reference which already exists.',
    testInputs: 'Existing Sanction Reference',
    expectedResult: 'System should allow selection and usage of an already existing sanction reference.',
    actualResult: 'System allows using the same existing sanction reference.',
    status: 'pass',
  },
  {
    testCaseId: 'TC24',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate date restriction in Sanction Bulk Upload',
    testCases: 'Verify that system does not allow sanction bulk upload when future date is provided as past system date.',
    testInputs: 'Sanction Bulk Upload',
    expectedResult: 'System should throw validation error and restrict upload if future date is entered as past system date.',
    actualResult: 'System throws validation error and does not allow bulk upload with incorrect date.',
    status: 'pass',
  },
  {
    testCaseId: 'TC25',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate "Has Sub Limit" restriction for ECB instrument',
    testCases: 'Verify that "Has Sub Limit" should be set to NO for ECB instrument and system applies validation accordingly.',
    testInputs: 'Instrument = ECB',
    expectedResult: 'System should restrict "Has Sub Limit" to NO for ECB instrument and throw validation error if set otherwise.',
    actualResult: 'System enforces "Has Sub Limit" as NO for ECB and throws validation error when attempted otherwise.',
    status: 'pass',
  },
  {
    testCaseId: 'TC26',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate mandatory currency field in sanction',
    testCases: 'Verify that system throws validation error when "Currency" column is kept blank.',
    testInputs: 'Currency = Blank',
    expectedResult: 'System should show validation error and restrict submission if "Currency" field is left blank.',
    actualResult: 'System throws proper validation error when "Currency" field is kept blank.',
    status: 'pass',
  },
  {
    testCaseId: 'TC27',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate consistency of main break-up number across sheets',
    testCases: 'Verify that system throws validation error when different main break-up numbers are used in both sheets.',
    testInputs: 'Mismatched Main Break-up Number',
    expectedResult: 'System should not allow mismatch and should show validation error if main break-up numbers are different across sheets.',
    actualResult: 'System throws validation error when different main break-up numbers are used in both sheets.',
    status: 'pass',
  },
  {
    testCaseId: 'TC28',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate currency restriction for non-ECB instruments during bulk upload',
    testCases: 'Verify that system throws validation error when currency other than base company currency is used for instruments except ECB during bulk upload.',
    testInputs: 'Non-ECB instrument with FCY',
    expectedResult: 'For all instruments except ECB, only base company currency should be allowed. System should throw validation error during import if currency is different from base currency.',
    actualResult: 'System throws validation error during bulk upload when non-base currency is used for instruments other than ECB.',
    status: 'pass',
  },
  {
    testCaseId: 'TC29',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate restriction on multiple currencies in main break-up under same sanction reference',
    testCases: 'Verify that system does not allow multiple currencies in main break-up under the same sanction reference.',
    testInputs: 'Multiple currencies in Main Break-up',
    expectedResult: 'System should restrict adding multiple currencies in main break-up for the same sanction reference and throw validation error.',
    actualResult: 'System does not allow multiple currencies in main break-up under same sanction reference and throws validation error.',
    status: 'pass',
  },
  {
    testCaseId: 'TC30',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate multiple currency restriction for ECB deals under same sanction reference',
    testCases: 'Verify that system does not allow creating multiple ECB deals in different currencies under the same sanction reference.',
    testInputs: 'Multiple ECB deals with different currencies',
    expectedResult: 'System should restrict creating multiple ECB deals with different currencies under the same sanction reference and show proper validation error.',
    actualResult: 'System restricts creating multiple ECB deals with different currencies under the same sanction reference.',
    status: 'pass',
  },
  {
    testCaseId: 'TC31',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate FCY usage for ECB instrument irrespective of base currency',
    testCases: 'Verify that system allows using FCY in ECB instrument even if it is different from base company currency.',
    testInputs: 'ECB instrument with FCY',
    expectedResult: 'System should allow FCY selection for ECB instrument regardless of base currency.',
    actualResult: 'System allows using FCY for ECB instrument irrespective of base currency.',
    status: 'pass',
  },
  {
    testCaseId: 'TC32',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate sub break-up amount against main break-up for fungible instrument',
    testCases: 'Verify that system does not allow sub break-up amount to exceed main break-up amount in fungible instrument.',
    testInputs: 'Sub Break-up Amount > Main Break-up Amount',
    expectedResult: 'System should throw validation error if sub break-up amount exceeds main break-up amount.',
    actualResult: 'System throws validation error when sub break-up amount exceeds main break-up amount in fungible instrument.',
    status: 'pass',
  },
  {
    testCaseId: 'TC33',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate presence of break-up details for sanction in other sheets',
    testCases: 'Verify that system throws validation error when a sanction is present in basic details but has no related break-up details in other sheets.',
    testInputs: 'Missing Break-up Details',
    expectedResult: 'System should restrict submission and show validation error if break-up details for the sanction are missing in other sheets.',
    actualResult: 'System throws validation error when sanction in basic details has no corresponding break-up in other sheets.',
    status: 'pass',
  },
  {
    testCaseId: 'TC34',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate multiple sanction references with different currencies',
    testCases: 'Verify that system allows creation of multiple sanction references with different currencies.',
    testInputs: 'Multiple Sanction References with different currencies',
    expectedResult: 'System should allow multiple sanction references even if the currencies are different.',
    actualResult: 'System allows creation of multiple sanction references with different currencies.',
    status: 'pass',
  },
  {
    testCaseId: 'TC35',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate file type/report during upload',
    testCases: 'Verify that system throws validation error when user tries to upload a file/report other than the allowed sanction bulk upload template.',
    testInputs: 'Invalid file/report template',
    expectedResult: 'System should restrict upload and show validation error if an incorrect report or file type is used.',
    actualResult: 'System throws validation error and does not allow upload of a different report.',
    status: 'pass',
  },
  {
    testCaseId: 'TC36',
    testModule: 'sanction bulk',
    featureTab: 'ECB/Sanction',
    testScenario: 'Validate dependency of sub break-up on main break-up',
    testCases: 'Verify that system does not allow adding sub break-up if there is no corresponding main break-up.',
    testInputs: 'Sub Break-up without Main Break-up',
    expectedResult: 'System should restrict submission and show validation error if sub break-up is added without a main break-up.',
    actualResult: 'System does not allow adding sub break-up without main break-up and throws validation error.',
    status: 'pass',
  },

  // 5. CC/OD and Bank Balance Master
  {
    testCaseId: 'TC01',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the Bank Balance Master header is updated to "Actual Closing Balance".',
    testCases: 'Verify that the header name in the Bank Balance Master screen/report is displayed as "Actual Closing Balance" instead of the previous header name.',
    testInputs: 'Bank Balance Master screen',
    expectedResult: 'The system should display the header as "Actual Closing Balance" in the Bank Balance Master section.',
    actualResult: 'The header is successfully updated and displayed as "Actual Closing Balance".',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the updated closing balance is reflected in Cashflow on the same effective date and interest calculation starts from that date.',
    testCases: 'Verify that when the closing balance is updated for a specific date, the same balance is reflected in the Cashflow on that date and interest calculation begins from the effective date of the balance update.',
    testInputs: 'Closing Balance Update',
    expectedResult: 'The updated closing balance should be visible in the Cashflow on the same date it is updated, and interest calculation should start from that date onward.',
    actualResult: 'The updated closing balance is reflected in the Cashflow on the same date, and interest calculation starts from the effective date as expected.',
    status: 'pass',
  },
  {
    testCaseId: 'TC03',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that a negative bank account balance cannot be updated after the sanction validity period has expired.',
    testCases: 'Verify that the system restricts users from updating the bank account balance with a negative value after the sanction validity date has passed.',
    testInputs: 'Negative Balance after Sanction Validity Expiry',
    expectedResult: 'The system should not allow updating the bank account balance with a negative value after the sanction validity period and should display an appropriate validation message.',
    actualResult: 'The system prevents the update of a negative bank account balance after the sanction validity period and displays the appropriate validation message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC04',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that a negative bank balance cannot be updated for an account that does not have any CC/OD deal associated with it.',
    testCases: 'Verify that the system restricts users from updating the bank balance as a negative value for an account where no CC/OD deal has been created.',
    testInputs: 'Negative Balance without CC/OD Deal',
    expectedResult: 'The system should not allow a negative bank balance update for an account without an associated CC/OD deal and should display an appropriate validation message.',
    actualResult: 'The system prevents the negative bank balance update for an account without a CC/OD deal and displays the appropriate validation message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC05',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that a positive bank balance can be updated for an account where no CC/OD deal has been created.',
    testCases: 'Verify that the system allows updating a positive bank balance for an account that is not linked to any CC/OD deal.',
    testInputs: 'Positive Balance without CC/OD Deal',
    expectedResult: 'The system should allow the user to update a positive bank balance for an account even if no CC/OD deal has been created for that account.',
    actualResult: 'The system successfully allows updating a positive bank balance for an account with no associated CC/OD deal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC06',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the system restricts updating a CC/OD bank balance beyond the sanctioned limit.',
    testCases: 'Verify that when a user attempts to update the bank balance amount for a CC/OD account with a value greater than the sanctioned limit, the system displays an appropriate validation message.',
    testInputs: 'CC/OD Balance > Sanctioned Limit',
    expectedResult: 'The system should not allow the bank balance amount to exceed the sanctioned limit for a CC/OD account and should display a validation message indicating that the entered amount exceeds the sanctioned limit.',
    actualResult: 'The system prevents updating the bank balance amount beyond the sanctioned limit and displays the appropriate validation message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC07',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that utilisation is updated correctly after repayment and reflected in the sanction details.',
    testCases: 'Verify that when a repayment is processed, the utilised amount is reduced accordingly and the updated utilisation is reflected in both the repayment details and the sanction record.',
    testInputs: 'CC/OD Repayment',
    expectedResult: 'The system should correctly update the utilisation amount after repayment and display the revised utilisation value in the sanction details.',
    actualResult: 'The utilisation amount is updated correctly after repayment and is accurately reflected in the sanction details.',
    status: 'pass',
  },
  {
    testCaseId: 'TC08',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the closing balance on the sanction validity date for a linked CC/OD deal is either zero or positive.',
    testCases: 'Verify that for a CC/OD deal linked to a sanction, the closing balance on the sanction validity date cannot be negative and remains either zero or positive.',
    testInputs: 'Closing Balance on Sanction Validity Date',
    expectedResult: 'The system should ensure that the closing balance on the sanction validity date is either 0 or a positive value for the linked CC/OD deal.',
    actualResult: 'The closing balance on the sanction validity date is maintained as zero or positive for the linked CC/OD deal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC09',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that borrowing is reflected in the ALM Treasury Report from the date the bank balance is updated.',
    testCases: 'Verify that when a bank balance is updated, the corresponding borrowing amount is shown in the ALM Treasury Report on the same effective date of the balance update.',
    testInputs: 'ALM Treasury Report',
    expectedResult: 'The system should display the borrowing amount in the ALM Treasury Report starting from the date on which the bank balance is updated.',
    actualResult: 'The borrowing amount is accurately reflected in the ALM Treasury Report on the same date as the bank balance update.',
    status: 'pass',
  },
  {
    testCaseId: 'TC10',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the borrowing amount is correctly reflected in the Borrowing Register Report after the bank balance update.',
    testCases: 'Verify that when a bank balance is updated, the corresponding borrowing entry is displayed in the Borrowing Register Report from the effective date of the balance update.',
    testInputs: 'Borrowing Register Report',
    expectedResult: 'The system should show the borrowing amount in the Borrowing Register Report on the same date the bank balance is updated.',
    actualResult: 'The borrowing amount is correctly reflected in the Borrowing Register Report from the bank balance update date.',
    status: 'pass',
  },
  {
    testCaseId: 'TC11',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that bank balance updates through bulk import are correctly reflected in the Deal Cashflow UI.',
    testCases: 'Verify that when bank balances are updated using the bulk import functionality, the corresponding entries are accurately reflected in the Deal Cashflow UI.',
    testInputs: 'Bank Balance Bulk Import',
    expectedResult: 'The system should successfully process the bulk import and display the updated bank balance details in the Deal Cashflow UI from the effective date.',
    actualResult: 'The bank balance updates processed through bulk import are correctly reflected in the Deal Cashflow UI.',
    status: 'pass',
  },
  {
    testCaseId: 'TC12',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that the CC Bank Account dropdown in the Deal UI displays only the relevant bank accounts of the selected lender bank.',
    testCases: 'Verify that in the CC Bank Account field dropdown on the Deal UI, only those bank accounts of the Home Entity are displayed that belong to the bank selected as the lender bank for the CC/OD facility.',
    testInputs: 'CC Bank Account Dropdown',
    expectedResult: 'The system should display only the Home Entity bank accounts associated with the selected lender bank in the CC Bank Account dropdown.',
    actualResult: 'The CC Bank Account dropdown displays only the relevant Home Entity bank accounts linked to the selected lender bank.',
    status: 'pass',
  },
  {
    testCaseId: 'TC13',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that a bank account created for tracking purposes allows updating a positive bank balance in the Bank Balance Master.',
    testCases: 'Verify that when a bank account is created only for tracking purposes, the user is able to update a positive bank balance in the Bank Balance Master.',
    testInputs: 'Tracking-Purpose Bank Account (Positive Balance)',
    expectedResult: 'The system should allow updating a positive bank balance in the Bank Balance Master for a bank account created for tracking purposes.',
    actualResult: 'The positive bank balance is successfully updated in the Bank Balance Master for the tracking-purpose bank account.',
    status: 'pass',
  },
  {
    testCaseId: 'TC14',
    testModule: 'CC/OD',
    featureTab: 'CC/OD and Bank Balance',
    testScenario: 'Validate that a negative bank balance cannot be updated in the Bank Balance Master for a bank account created only for tracking purposes.',
    testCases: 'Verify that when a bank account is created solely for tracking purposes, the system restricts the user from updating a negative bank balance in the Bank Balance Master.',
    testInputs: 'Tracking-Purpose Bank Account (Negative Balance)',
    expectedResult: 'The system should restrict updating a negative bank balance for a tracking-purpose bank account and should display an appropriate validation message.',
    actualResult: 'The system prevents the update of a negative bank balance and displays the appropriate validation message.',
    status: 'pass',
  },

  // 6. Mutual Fund — Split Action / Initiate Action
  {
    testCaseId: 'TC01',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate the availability and editability of the Split Action in an MF deal.',
    testCases: 'Verify that the Split Action is visible and clickable under the Initiate Action option for an MF deal, and all fields available in the Split Action are editable.',
    testInputs: 'Initiate Action -> Split Action',
    expectedResult: 'The Split Action should be visible and clickable under Initiate Action, and all fields in the Split Action should be editable.',
    actualResult: 'The Split Action was visible and clickable under Initiate Action, and all fields in the Split Action were editable.',
    status: 'pass',
  },
  {
    testCaseId: 'TC02',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Split Ratio Entry',
    testCases: 'Verify that the user can enter the applicable New:Old split ratio while performing a split action from an existing ISIN to a new ISIN.',
    testInputs: 'Ratio (New:Old)',
    expectedResult: 'The user should be able to enter and edit the applicable split ratio in the Ratio (New:Old) field.',
    actualResult: 'The applicable New:Old split ratio was entered successfully in the Split Action.',
    status: 'pass',
  },
  {
    testCaseId: 'TC03',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate AMC filtering in the Split Out From section during the MF Split Action.',
    testCases: 'Verify that while performing the Split Action for a selected Mutual Fund (Split In), the Split Out From dropdown displays only the schemes belonging to the same AMC as the selected Mutual Fund (Split In).',
    testInputs: 'Split Out From Dropdown',
    expectedResult: 'The Split Out From dropdown should display only the schemes belonging to the same AMC as the selected Mutual Fund (Split In). Schemes belonging to any other AMC should not be available for selection.',
    actualResult: 'The Split Out From dropdown displayed only the schemes belonging to the same AMC as the selected Mutual Fund, and schemes from other AMCs were not available for selection.',
    status: 'pass',
  },
  {
    testCaseId: 'TC04',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Split In Units Calculation',
    testCases: 'Verify that the units allocated under the Split In section are calculated correctly based on the applied split ratio.',
    testInputs: 'Existing Units & Applied Split Ratio',
    expectedResult: 'The system should calculate and display the correct number of Split In units based on the existing units and the entered split ratio.',
    actualResult: 'The Split In units were calculated and displayed correctly based on the applied split ratio.',
    status: 'pass',
  },
  {
    testCaseId: 'TC05',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Investment Holding Details',
    testCases: 'Verify that the existing MF deal\'s holding details are displayed correctly in the Investment Holding Details table during the split action.',
    testInputs: 'Investment Holding Details Table',
    expectedResult: 'The Investment Holding Details table should display the correct transaction date, NAV date, units, and purchase NAV for the existing MF deal.',
    actualResult: 'The existing MF deal\'s holding details were displayed correctly in the Investment Holding Details table.',
    status: 'pass',
  },
  {
    testCaseId: 'TC06',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate the Value Date in the Split Out and Split In transaction.',
    testCases: 'Verify that the Value Date in the Split Out deal is validated against the Transaction Date, and the Value Date in the Split In deal is automatically fetched from the Split Out transaction.',
    testInputs: 'Value Date & Transaction Date',
    expectedResult: 'In the Split Out deal, the Value Date should be after the Transaction Date. In the Split In deal, the Value Date should be automatically fetched from the corresponding Split Out transaction.',
    actualResult: 'The Value Date in the Split Out deal was validated successfully against the Transaction Date, and the Value Date in the Split In deal was automatically fetched from the Split Out transaction.',
    status: 'pass',
  },
  {
    testCaseId: 'TC07',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate NAV Calculation Based on Split Ratio.',
    testCases: 'Verify that the NAV for the new ISIN is calculated correctly based on the entered split ratio.',
    testInputs: 'New ISIN NAV & Split Ratio',
    expectedResult: 'The system should calculate and display the correct NAV for the new ISIN based on the applied split ratio.',
    actualResult: 'The NAV for the new ISIN was calculated and displayed correctly based on the applied split ratio.',
    status: 'pass',
  },
  {
    testCaseId: 'TC08',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate the Holding Summary after performing the MF Split Action.',
    testCases: 'Verify that after successfully performing the Split Action, all values displayed in the Holding Summary for both the existing (Split Out) deal and the new (Split In) deal are updated and displayed correctly.',
    testInputs: 'Holding Summary (Total Units, Average Purchase NAV, Total Investment Amount, Current Market Value, Unrealised/Realised P&L, XIRR)',
    expectedResult: 'After the Split Action is completed, the Holding Summary should display the correct values for both the Split Out and Split In deals, including Total Units, Average Purchase NAV, Total Investment Amount, Current Market Value, Unrealised Profit/Loss, Realised Profit/Loss, and XIRR.',
    actualResult: 'After performing the Split Action, all values in the Holding Summary for both the Split Out and Split In deals were updated correctly and displayed as expected.',
    status: 'pass',
  },
  {
    testCaseId: 'TC09',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate transaction history after performing the MF Split Action.',
    testCases: 'Verify that after successfully performing the Split Out and Split In actions, the transaction history of both the existing deal and the new deal is updated correctly with all split-related details.',
    testInputs: 'Transaction History',
    expectedResult: 'The Split Out transaction should be recorded in the existing MF deal history, and the Split In transaction should be recorded in the new MF deal history with correct transaction date, action type, units, NAV, and investment amount.',
    actualResult: 'After performing the Split Out and Split In actions, the transaction history of both the existing and new MF deals was updated correctly, and all split-related details were displayed accurately.',
    status: 'pass',
  },
  {
    testCaseId: 'TC10',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Split Out action on a deal with pending authorization of the first investment transaction.',
    testCases: 'Verify that the system does not allow the user to perform a Split Out action on an MF deal where the first investment transaction is in Pending Authorization status.',
    testInputs: 'First Investment Transaction = Pending Authorization',
    expectedResult: 'The system should not allow the Split Out action on a deal whose first investment transaction is pending authorization. An appropriate validation/error message should be displayed, indicating that the deal cannot be split until the investment transaction is authorized.',
    actualResult: 'When attempting to perform the Split Out action on a deal with the first investment transaction in Pending Authorization status, the system prevented the action and displayed the appropriate validation message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC11',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Split Out behavior when a Redemption transaction is pending authorization.',
    testCases: 'Verify that the system allows the user to perform a Split Out action on an MF deal even when a Redemption transaction is in Pending Authorization status, and validate the behavior while authorizing the pending Redemption transaction after the Split Out.',
    testInputs: 'Redemption Transaction = Pending Authorization',
    expectedResult: 'The system should allow the Split Out action if there are sufficient existing units, irrespective of the pending Redemption authorization. After the Split Out is completed, if authorizing the pending Redemption transaction results in a negative unit balance, the system should prevent the authorization and display an appropriate validation/error message indicating insufficient units in the split out deal.',
    actualResult: 'The system allowed the Split Out action on the deal with a pending Redemption transaction. However, after the Split Out, authorizing the pending Redemption transaction would result in a negative unit balance, and the system prevented the authorization with an appropriate validation message.',
    status: 'pass',
  },
  {
    testCaseId: 'TC12',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate the available actions for a deal after performing the Split Out action.',
    testCases: 'Verify that after all units of an MF deal have been Split Out, only the MF Modification action is available under Initiate Action. Other transaction actions such as Investment, Redemption, and Switch should not be available.',
    testInputs: 'Initiate Action Menu after Split Out',
    expectedResult: 'After the Split Out action, the Initiate Action menu should display only the MF Modification option. The Investment, Redemption, Switch, and any other transaction-related actions should not be visible or available for the Split Out deal.',
    actualResult: 'After the Split Out action, only the MF Modification option was available under Initiate Action. The Investment, Redemption, Switch, and other transaction-related actions were not displayed for the Split Out deal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC13',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Split In Action for Already Split In Deal',
    testCases: 'Verify that Split In action cannot be performed again on a deal where Split In has already been completed.',
    testInputs: 'Already Split In Deal',
    expectedResult: 'The system should remove the Split Action option from the Initiate Action menu for a deal where Split In has already been performed.',
    actualResult: 'The Split Action option was correctly removed from the Initiate Action menu after Split In was performed on the deal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC14',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Scheme Availability Based on Split In Deal',
    testCases: 'Verify that, while performing the Split Action, only those deals are available in the Split Out Scheme from which the Plan, Option, and Fund Name match with the Split In deal.',
    testInputs: 'Plan, Option, and Fund Name matching',
    expectedResult: 'The system should display only those deals in the Split Out Scheme where the Plan, Option, and Fund Name are the same as the selected Split In deal.',
    actualResult: 'The system correctly displayed only those deals in the Split Out Scheme where the Plan, Option, and Fund Name matched with the selected Split In deal.',
    status: 'pass',
  },
  {
    testCaseId: 'TC15',
    testModule: 'Mutual Fund',
    featureTab: 'split action',
    testScenario: 'Validate Previous Transactions in Split In Deal',
    testCases: 'Verify that the Split In deal does not have any previous transactions before performing the Split Action.',
    testInputs: 'Split In Deal with Existing Transactions',
    expectedResult: 'The system should allow the Split In transaction only when there are no previous transactions in the Split In deal. If any transaction already exists in the deal, the system should not allow the Split Action and should display an appropriate validation message.',
    actualResult: 'The system correctly restricted the Split Action when a previous transaction existed in the Split In deal and displayed the appropriate validation message.',
    status: 'pass',
  },
];
